import { UserProfile, ExerciseItem, Attempt, StudentProgress, ClassInfo, TeacherReport } from '../types';
import { TEACHER_CONFIG } from './constants';

export const DEMO_TEACHER: UserProfile = {
  id: 'teacher-solene-depibrac',
  email: TEACHER_CONFIG.email,
  firstName: TEACHER_CONFIG.firstName,
  lastName: TEACHER_CONFIG.lastName,
  role: 'teacher',
  classId: TEACHER_CONFIG.classId,
  className: TEACHER_CONFIG.className,
  createdAt: '2026-09-01T08:00:00.000Z',
};

export const DEMO_CLASS: ClassInfo = {
  id: TEACHER_CONFIG.classId,
  name: 'CM2',
  teacherId: DEMO_TEACHER.id,
  teacherName: TEACHER_CONFIG.fullName,
  studentCount: 0,
  averageSuccessRate: 0,
  totalExercisesCompleted: 0,
  createdAt: '2026-09-01T08:00:00.000Z',
};

// ZERO fake students: only real students registered by the user
export const DEMO_STUDENTS: UserProfile[] = [];

// Curricular starter exercises for CM2 that Gemini or the user can practice with
export const INITIAL_EXERCISES: ExerciseItem[] = [
  {
    id: 'ex-frac-1',
    subject: 'Mathématiques',
    skill: 'Fractions',
    difficulty: 'facile',
    question: 'Quelle fraction est la plus grande ?',
    type: 'qcm',
    options: ['1/2', '3/4', '2/5', '1/4'],
    correctAnswer: '3/4',
    explanation: '3/4 représente 0,75 alors que 1/2 représente 0,5 et 2/5 représente 0,4. 3/4 est donc la plus grande.',
  },
  {
    id: 'ex-frac-2',
    subject: 'Mathématiques',
    skill: 'Fractions',
    difficulty: 'moyen',
    question: 'Quelle fraction est égale à 2/4 ?',
    type: 'qcm',
    options: ['1/3', '1/2', '3/6', '4/6'],
    correctAnswer: '1/2',
    explanation: 'En divisant le numérateur et le dénominateur par 2 : 2/4 = (2÷2)/(4÷2) = 1/2.',
  },
  {
    id: 'ex-prob-1',
    subject: 'Mathématiques',
    skill: 'Problèmes',
    difficulty: 'moyen',
    question: 'Léa achète 3 livres à 8 € chacun et un carnet à 5 €. Elle paie avec un billet de 50 €. Combien la caissière lui rend-elle ?',
    type: 'numeric',
    correctAnswer: '21',
    explanation: 'Total des achats : (3 × 8 €) + 5 € = 24 € + 5 € = 29 €. Monnaie rendue : 50 € - 29 € = 21 €.',
  },
  {
    id: 'ex-calc-1',
    subject: 'Mathématiques',
    skill: 'Calcul',
    difficulty: 'facile',
    question: 'Combien font 35 × 10 ?',
    type: 'numeric',
    correctAnswer: '350',
    explanation: 'Pour multiplier un nombre entier par 10, on ajoute un 0 à sa droite : 35 × 10 = 350.',
  },
  {
    id: 'ex-calc-2',
    subject: 'Mathématiques',
    skill: 'Calcul',
    difficulty: 'moyen',
    question: 'Calcule mentalement : 25 × 4 = ?',
    type: 'numeric',
    correctAnswer: '100',
    explanation: '25 × 4 est un calcul repère indispensable en CM2 : 25 + 25 + 25 + 25 = 100.',
  },
  {
    id: 'ex-geom-1',
    subject: 'Mathématiques',
    skill: 'Géométrie',
    difficulty: 'facile',
    question: 'Combien d\'angles droits possède un rectangle ?',
    type: 'numeric',
    correctAnswer: '4',
    explanation: 'Par définition, un rectangle possède toujours 4 angles droits et des côtés opposés égaux deux à deux.',
  },
  {
    id: 'ex-gram-1',
    subject: 'Français',
    skill: 'Grammaire',
    difficulty: 'facile',
    question: 'Dans la phrase « Le jeune lion bondit agilement », quelle est la nature du mot « agilement » ?',
    type: 'qcm',
    options: ['Un verbe', 'Un adverbe', 'Un adjectif', 'Un nom commun'],
    correctAnswer: 'Un adverbe',
    explanation: '« Agilement » est un adverbe de manière qui précise comment le lion bondit.',
  },
  {
    id: 'ex-conj-1',
    subject: 'Français',
    skill: 'Conjugaison',
    difficulty: 'facile',
    question: 'Conjugue le verbe « chanter » au futur avec « nous » : Nous ...',
    type: 'qcm',
    options: ['chantons', 'chanterons', 'chantions', 'chanteront'],
    correctAnswer: 'chanterons',
    explanation: 'Au futur simple, la terminaison avec « nous » est toujours « -ons » ajoutée à l\'infinitif : nous chanterons.',
  },
  {
    id: 'ex-ortho-1',
    subject: 'Français',
    skill: 'Orthographe',
    difficulty: 'facile',
    question: 'Complète : « Les enfants ... contents de leur journée. »',
    type: 'qcm',
    options: ['son', 'sont', 'sons'],
    correctAnswer: 'sont',
    explanation: '« Sont » est le verbe être conjugué au présent (on peut le remplacer par « étaient » : les enfants étaient contents).',
  },
];

// ZERO fake attempts: only real attempts performed by actual students
export const DEMO_ATTEMPTS: Attempt[] = [];

// ZERO fake progress: real students start with 0% and empty progress
export const DEMO_PROGRESS: StudentProgress[] = [];

// ZERO fake reports: only real reports generated by Solène
export const DEMO_REPORT: TeacherReport | null = null;
